from game.piece import Piece
from game.move import Move

## Board is the "sanity check" of the project. The robot will compare it to the board generated by the computer-vision model 

class Board:
    def __init__(self):
        self.board = [[None for _ in range(8)] for _ in range(8)]
        
        self.setup()
        
    # board state
    def setup(self):
        """Resets all pieces to their traditional location on an 8x8 checkers board"""
        for y in range(0, 3):
            for x in range(0, 8):
                if not self.is_unplayable_space(x,y):
                    self.set(x, y, Piece(Piece.BLACK)) 
                    
        for y in range(5,8):
            for x in range(0,8):
                if not self.is_unplayable_space(x,y):
                    self.set(x,y, Piece(Piece.WHITE))
    
    # low-level grid interactions
    def get(self, x: int, y: int) -> Piece | None:
        """Returns the object currently occupying a coordinate on the board, or 'None' if it is empty"""
        if self.is_unplayable_space(x,y):
            return None
        return self.board[y][x]
    
    def set(self, x: int, y: int, piece: Piece, force = False):
        """Sets a specific coordinate on the board to the specified object. Use force to ignore invariants."""
        self.board[y][x] = piece

        if self.is_unplayable_space(x,y):
            raise ValueError("Tried to place something in an unplayable space at " + str(x) + str(y))
    
    # board-piece interaction
    def move(self, x1: int, y1: int, x2: int, y2: int, force = False) -> bool:
        """If valid, moves a piece to a given position. Automatically promotes any pieces that are at the opposing end of the board."""
        
        moved_piece = self.get(x1,y1)
        legal_moves = self.get_legal(x1,y1)

        valid = False
        for move in legal_moves:
            if (x2,y2) in move.path:
                killed_pieces = move.kills
                valid = True

        if not (valid or force):
            return False

        # move to designated position
        self.set(x1,y1,None)
        self.set(x2,y2,moved_piece)

        # kill all pieces that should be killed
        for piece in killed_pieces:
            self.set(piece[0], piece[1], None)

        # if at the end of board, promote
        if (moved_piece.color == Piece.BLACK and y2 == 7) or (moved_piece.color == Piece.WHITE and y2 == 0):
            moved_piece.promote()

            return True
        else: # move not valid
            return False
    
    def promote(self, x: int, y: int) -> bool:
        """Promotes the piece on a given x,y coordinate to a king"""
        if self.is_occupied(x,y):
            self.get(x,y).promote()
            return True
        return False
    
    def get_legal(self, x, y, chained_piece = None, jumped = None) -> list[Move]:
        """Returns a list of legal moves from a given position"""
        legal_moves = [] # tuple(int, int)

        move_options = {
            Piece.BLACK: [(1,1), (-1,1)],
            Piece.WHITE: [(1,-1), (-1,-1)]
        }

        if jumped is None:
            jumped = []
        
        piece = self.get(x,y)
        if piece is None:
            piece = chained_piece

            if piece is None:
                print("Tried to find legal moves for a piece, but there is no piece on that tile! Tile: (" + str(x) + "," + str(y) + ")")
                return []

        if piece.is_king:
            dirs = move_options[Piece.BLACK] + move_options[Piece.WHITE]
        else:
            dirs = move_options[piece.color]

        for dir in dirs:
            tested_x = x + dir[0]
            tested_y = y + dir[1]

            if self.is_unplayable_space(tested_x, tested_y):
                continue
        
            space = self.get(tested_x, tested_y)

            if space is not None:
                if space.color == piece.color:
                    continue
                
                kill_x, kill_y = tested_x, tested_y
                tested_x += dir[0]
                tested_y += dir[1]

                if (kill_x, kill_y) in jumped:
                    continue
                
                if self.is_unplayable_space(tested_x, tested_y) or self.get(tested_x, tested_y) is not None:
                    continue
                
                next_moves = self.get_legal(tested_x, tested_y, piece, jumped + [(kill_x, kill_y)])
                
                if next_moves:
                    for next_move in next_moves:
                        chained = Move()
                        chained.path = [(tested_x, tested_y)] + next_move.path
                        chained.kills = [(kill_x, kill_y)] + next_move.kills
                        legal_moves.append(chained)
                else:
                    move = Move()
                    move.path = [(tested_x, tested_y)]
                    move.kills = [(kill_x, kill_y)]
                    legal_moves.append(move)
                
                continue
            else:
                legal_moves.append(Move([(tested_x, tested_y)]))
            
        return self.filter_forced_jumps(legal_moves)
    
    def filter_forced_jumps(self, jumps: list[Move]) -> list[Move]:
        """If there are killing jumps to be made, filter out any non-applicable jumps"""
        kill_jumps = []

        for jump in jumps:
            if len(jump.kills) > 0:
                kill_jumps.append(jump)

        if len(kill_jumps) > 0:
            return kill_jumps
        return jumps

         
    def get_every_legal(self, color) -> list[Move]:
        """Returns every legal position a color can make"""
        pieces = self.get_all_pieces_of_team(color)
        legal_moves = [[] for piece in pieces]
        
        for piece in range(0, len(pieces)):
            legal_moves[piece] = self.get_legal(pieces[piece][0], pieces[piece][1])
        
        return legal_moves
    
    # game logic
    
    def has_won(self, color) -> bool:
        """Returns whether a team has won the game or not"""
        if color == Piece.BLACK and (self.get_num_pieces(Piece.WHITE) or len(self.self.get_every_legal(Piece.WHITE))) == 0:
            return True
        elif color == Piece.WHITE and (self.get_num_pieces(Piece.BLACK) or len(self.self.get_every_legal(Piece.BLACK))) == 0:
            return True
        else:
            return False
        
    def get_all_pieces(self):
        """Returns a list of every piece currently on the board"""
        return self.get_all_pieces_of_team(Piece.WHITE) + self.get_all_pieces_of_team(Piece.BLACK)
    
    def get_all_pieces_of_team(self, color) -> list[tuple[int, int]]:
        """Returns a list of all pieces belonging to a specific color"""
        pieces = []
        
        for y in range(0,8):
            for x in range(0,8):
                if self.is_occupied(x,y):
                    occupant = self.get(x,y)
                    if isinstance(occupant, Piece) and occupant.color == color:
                        pieces.append((x,y))
        return pieces
    
    def get_num_pieces(self, color) -> int:
        """Returns the number of alive pieces of this color"""
        return len(self.get_all_pieces_of_team(color))

    # helpers
    def is_unplayable_space(self, x: int, y: int) -> bool:
        """Returns True if a space is an unused, out of bounds or otherwise unplayable"""
        if self.is_out_of_bounds(x,y):
            return True
        elif (x + y) % 2 == 1:
            return False
        else:
            return True
        
    def is_occupied(self, x, y) -> bool:
        """Returns True if a space is occupied"""
        return self.get(x,y) != None
    
    def is_out_of_bounds(self,x,y) -> bool:
        "Returns True if a space is off the board"
        return x > 7 or x < 0 or y > 7 or y < 0
    
    # overrides    
    def __str__(self):
        board_str = ""
        for y, row in enumerate(self.board):
            for x, piece in enumerate(row):
                if isinstance(piece, Piece):
                    board_str += str(piece) + " "
                elif not self.is_unplayable_space(x, y):
                    board_str += "|||| "
                elif piece is None:
                    board_str += "---- "
                    
            board_str += "\n"
        return board_str